[package]
name = "nandpromax"
version = "0.0.1"
edition = "2021"
[lib]
name = "libnandpromax"
crate-type = ["cdylib"]

[features]
default = []
libftdi = ["ftdi-embedded-hal/ftdi-libusb1-sys"]

[dependencies.ftdi-embedded-hal]
version = "0.24.0"
optional = true
features = ["libftd2xx", "libftd2xx-static"]

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
serialport = "4"
rusb = "0.9"
eh0 = { package = "embedded-hal", version = "0.2.7", features = ["unproven"] }
eh1 = { package = "embedded-hal", version = "1" }
ehnb1 = { package = "embedded-hal-nb", version = "1" }
rusb = "0.9"
